### PR TITLE
Add new version 1.4.0

### PR DESCRIPTION
**Pull request by pipo02mix**
Towards https://github.com/giantswarm/giantswarm/issues/4623

### CODE REVIEW

**Comment by pipo02mix** [comment]
@indyfree what I need to do currently to have it deployed in the tenants? update cluster operator chart details?

**Comment by pipo02mix** [comment]
Fmt fixed here https://github.com/giantswarm/kubernetes-kube-state-metrics/pull/33

**Comment by indyfree** [comment]
@pipo02mix If you don't increase the minor version here: https://github.com/giantswarm/kubernetes-kube-state-metrics/tree/master/helm/kubernetes-kube-state-metrics-chart/Chart.yaml#L5 changes get rolled automatically :+1: 

If you increase to e.g. `0.2.0` you have to switch the channel for the chart `cluster-operator`.

**Comment by pipo02mix** [comment]
ok I see, but to be aligned with the process, what I have to do? if I increase app version it should translate into an increase in the chart version too?

**Pull request merged**
